In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 442.7 kB/s eta 0:00:27
   - -------------------------------------- 0.5/12.3 MB 442.7 kB/s eta 0:00:27
   - -------------------------------------- 0.5/12.3 MB 442.7 kB/s eta 0:00:27
   -- ------------------------------------- 0.8/12.3 MB 442.0 kB/s eta 0:00:27
   -- ------------------------------------- 0.8/12.3 MB 442.0 kB/s eta 0:00:27
   --- ------------------------------------ 1.0/12.3 MB 452.7 kB/s eta 0:00:25
   --- -----------------------------


[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [5]:
arr = np.array(
   [ [1,2,3,4],
    [5,6,7,8]]
)

In [6]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
listt = [10,20,30]

In [8]:
myarray = np.array(listt)

In [9]:
myarray

array([10, 20, 30])

In [10]:
myarray.shape

(3,)

In [11]:
arr.shape

(2, 4)

In [12]:
rows = arr.shape[0]

In [13]:
rows

2

In [14]:
col = arr.shape[1]
col

4

In [15]:
myarray.dtype

dtype('int64')

In [17]:
zeroarray = np.zeros(4,float)
zeroarray

array([0., 0., 0., 0.])

In [19]:
onearray = np.ones([5,5],int)
onearray

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
myrange = np.arange(0,50,2)
myrange

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [21]:
arr1 = np.array([[2,4,6],
                 [1,2,3]])
arr1

array([[2, 4, 6],
       [1, 2, 3]])

In [23]:
arr1*arr1

array([[ 4, 16, 36],
       [ 1,  4,  9]])

In [24]:
arr1*2

array([[ 4,  8, 12],
       [ 2,  4,  6]])