In [1]:
import numpy as np

In [2]:
ids = np.array([101,102,103,104,105])
heart_reat = np.array([72,110,95,130,88])

In [4]:
status = np.where(heart_reat>100, "critical" ,"stable")
print("patiant IDS: " , ids)
print("heart reat: " ,heart_reat)
print("status: " ,status)

patiant IDS:  [101 102 103 104 105]
heart reat:  [ 72 110  95 130  88]
status:  ['stable' 'critical' 'stable' 'critical' 'stable']


In [6]:
###========================================================

In [8]:
#####filling the missing data:

In [11]:
temp = np.array([36.5,37.2,0,38.1,0,36.8])
#zeros represent missing values
condition = temp != 0
filtered = temp[condition] #gathering of != temps in filtered
average_temp = filtered.mean()

clean_temp = np.where(temp == 0, average_temp,temp)
print(clean_temp)

[36.5  37.2  37.15 38.1  37.15 36.8 ]


In [14]:
#print temps > 37
condition2 = clean_temp > 37
filtered2 = clean_temp[condition2]
print(filtered2)

[37.2  37.15 38.1  37.15]


In [15]:
##############################

In [21]:
ages = np.array([25,26,30,28,24])
bp = np.array([120,130,200,150,122])

risk = np.where((ages>26)|(bp>130),"risk" , "normal")
print(risk)

['normal' 'normal' 'risk' 'risk' 'normal']


In [22]:
########salaries whth poness

In [25]:
salaries = np.array([400,600,550,300,700])
pones_salasies = np.where(salaries >= 500 , salaries+100 , salaries +50 )
print(pones_salasies)

[450 700 650 350 800]


In [26]:
###############################################

In [30]:
marks = np.array([89,75,60,82,68])
grades = np.where(marks >= 85 , "A" ,np.where(marks>70 , "B" , "C"))
print(grades)

['A' 'B' 'C' 'B' 'C']


In [32]:
marks = np.array([89,75,60,82,99,68])
grades = np.where(marks >= 85 , np.where(marks>=90 , "+A" , "-A")  ,np.where(marks>70 , "B" , "C"))
print(grades)

['-A' 'B' 'C' 'B' '+A' 'C']


In [4]:
############################################
import numpy as np

In [5]:
purchese = np.array([50,120,80,200,150])
np.where(purchese>100 , purchese*0.8 ,purchese*0.9)

array([ 45.,  96.,  72., 160., 120.])

In [6]:
############################################

In [8]:
heart_reat = np.array([80,130,110,140,90])
oxygen = np.array([95,85,88,98,89])
emergincy = np.where((heart_reat > 120) & (oxygen < 90 ) ,"emergincy" ,"normal")
print(emergincy)

['normal' 'emergincy' 'normal' 'normal' 'normal']


In [9]:
############################################################

In [14]:
arrayy = np.linspace(1, 70, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
print(arrayy)

[ 1.          2.40816327  3.81632653  5.2244898   6.63265306  8.04081633
  9.44897959 10.85714286 12.26530612 13.67346939 15.08163265 16.48979592
 17.89795918 19.30612245 20.71428571 22.12244898 23.53061224 24.93877551
 26.34693878 27.75510204 29.16326531 30.57142857 31.97959184 33.3877551
 34.79591837 36.20408163 37.6122449  39.02040816 40.42857143 41.83673469
 43.24489796 44.65306122 46.06122449 47.46938776 48.87755102 50.28571429
 51.69387755 53.10204082 54.51020408 55.91836735 57.32653061 58.73469388
 60.14285714 61.55102041 62.95918367 64.36734694 65.7755102  67.18367347
 68.59183673 70.        ]


In [15]:
print(arrayy.ndim)

1
