In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 442.7 kB/s eta 0:00:27
   - -------------------------------------- 0.5/12.3 MB 442.7 kB/s eta 0:00:27
   - -------------------------------------- 0.5/12.3 MB 442.7 kB/s eta 0:00:27
   -- ------------------------------------- 0.8/12.3 MB 442.0 kB/s eta 0:00:27
   -- ------------------------------------- 0.8/12.3 MB 442.0 kB/s eta 0:00:27
   --- ------------------------------------ 1.0/12.3 MB 452.7 kB/s eta 0:00:25
   --- -----------------------------


[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [5]:
arr = np.array(
   [ [1,2,3,4],
    [5,6,7,8]]
)

In [6]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
listt = [10,20,30]

In [8]:
myarray = np.array(listt)

In [9]:
myarray

array([10, 20, 30])

In [10]:
myarray.shape

(3,)

In [11]:
arr.shape

(2, 4)

In [12]:
rows = arr.shape[0]

In [13]:
rows

2

In [14]:
col = arr.shape[1]
col

4

In [15]:
myarray.dtype

dtype('int64')

In [17]:
zeroarray = np.zeros(4,float)
zeroarray

array([0., 0., 0., 0.])

In [19]:
onearray = np.ones([5,5],int)
onearray

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
myrange = np.arange(0,50,2)
myrange

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [21]:
arr1 = np.array([[2,4,6],
                 [1,2,3]])
arr1

array([[2, 4, 6],
       [1, 2, 3]])

In [23]:
arr1*arr1

array([[ 4, 16, 36],
       [ 1,  4,  9]])

In [24]:
arr1*2

array([[ 4,  8, 12],
       [ 2,  4,  6]])

In [7]:
arr2  = np.array([[2,4,6],
                 [1,2,3],
                 [4,3,2]])
arr2

NameError: name 'np' is not defined

In [8]:
import numpy as np

In [9]:
arr2  = np.array([[2,4,6],
                 [1,2,3],
                 [4,3,2]])
arr2

array([[2, 4, 6],
       [1, 2, 3],
       [4, 3, 2]])

In [10]:
A=np.array([[1,2,3],[4,5,6]])
print(A)
print('\n')
B=np.array([[7,8],[9,10],[11,12]])
print(B)
print('\n')
np.dot(A,B)

[[1 2 3]
 [4 5 6]]


[[ 7  8]
 [ 9 10]
 [11 12]]




array([[ 58,  64],
       [139, 154]])

In [13]:
lastelement = arr2[arr2.shape[0]-1]
lastelement
print(lastelement)

[4 3 2]


In [17]:
arr3 = np.array([1,2,3,4,5,6,7,8,9])
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr3[3:7]

array([4, 5, 6, 7])

In [23]:
arr2[ :2, :2 ]

array([[2, 4],
       [1, 2]])

In [25]:
arr3[0:2]=100
arr3

array([100, 100,   3,   4,   5,   6,   7,   8,   9])

In [28]:
reshapearray = arr3.reshape(3,3)
reshapearray

array([[100, 100,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [29]:
X = np.array([1,2,3,4])
Y = np.array([5,6,7,8])
np.concatenate([X,Y])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
grid = np.arange(16).reshape((4,4))
print(grid)
print("\n")
upper , lower = np.vsplit(grid, [2])
print( upper)
print("\n")
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[0 1 2 3]
 [4 5 6 7]]


[[ 8  9 10 11]
 [12 13 14 15]]


In [40]:
grid2 = np.arange(1,17).reshape((4,4))
print(grid2)
print("\n")
a , b, c = np.hsplit(grid, [2,3])
print("a=" ,a)
print("\n")
print("b=" ,b)
print("\n")
print("c=" ,c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


a= [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


b= [[ 2]
 [ 6]
 [10]
 [14]]


c= [[ 3]
 [ 7]
 [11]
 [15]]


# 

In [41]:
np.sqrt(c)

array([[1.73205081],
       [2.64575131],
       [3.31662479],
       [3.87298335]])

In [42]:
np.sqrt(a)

array([[0.        , 1.        ],
       [2.        , 2.23606798],
       [2.82842712, 3.        ],
       [3.46410162, 3.60555128]])

In [43]:
np.exp(c)

array([[2.00855369e+01],
       [1.09663316e+03],
       [5.98741417e+04],
       [3.26901737e+06]])

In [47]:
A = np.random.rand(1,100,20)
print(A)

[[[0.79515006 0.55408447 0.8558209  ... 0.51889613 0.44485811 0.41879727]
  [0.62135546 0.21808796 0.77963911 ... 0.54097376 0.39738847 0.60560213]
  [0.93118302 0.79530288 0.31582094 ... 0.76859548 0.972704   0.71217078]
  ...
  [0.1415508  0.06528825 0.42599035 ... 0.58568393 0.39444548 0.760133  ]
  [0.97468931 0.16735012 0.87793793 ... 0.77633049 0.4809746  0.82105847]
  [0.33265538 0.61316738 0.10795679 ... 0.65924409 0.85514445 0.36052546]]]


In [49]:
maxx = np.maximum(b,c)
maxx

array([[ 3],
       [ 7],
       [11],
       [15]])

In [50]:
adding = np.add(b,c)
adding

array([[ 5],
       [13],
       [21],
       [29]])

In [51]:
A = np.array([1,2,3,4])
B = np.array([100,200,300,400])
condition = np.array([True,True,False,False])
answer = np.where(condition,A,B)
answer

array([  1,   2, 300, 400])

In [52]:
numbers = np.array([1,-4,5,-7,8])
np.where(numbers<0 ,0 , numbers)

array([1, 0, 5, 0, 8])

In [55]:
a.sum(0)

array([24, 28])

In [56]:
a.var()

np.float64(20.25)

In [59]:
boolarray =np.array([True,True,False])
print(boolarray.any())

True


In [60]:
np.sort(c)

array([[ 3],
       [ 7],
       [11],
       [15]])

In [61]:
np.unique(boolarray)

array([False,  True])