In [1]:
import numpy as np

In [10]:
patients_data = np.array([
[45, 80, 200, 120],
[60, 90, 240, 140],
[30, 70, 180, 110],
[50, 85, 220, 130],
[65, 95, 260, 150]
])
patients_data

array([[ 45,  80, 200, 120],
       [ 60,  90, 240, 140],
       [ 30,  70, 180, 110],
       [ 50,  85, 220, 130],
       [ 65,  95, 260, 150]])

In [5]:
patients_data.shape

(5, 4)

In [7]:
patient_num = patients_data.shape[0]
patient_num

5

In [8]:
features = patients_data.shape[1]
features

4

In [9]:
##Q2. Accessing Data

In [16]:
first_patient_data = patients_data[patients_data.shape[1]-4]
first_patient_data

array([ 45,  80, 200, 120])

In [17]:
all_ages = patients_data[ : , 0:1]
all_ages

array([[45],
       [60],
       [30],
       [50],
       [65]])

In [19]:
blood_pressure_values = patients_data[ : , 3: ]
blood_pressure_values

array([[120],
       [140],
       [110],
       [130],
       [150]])

In [20]:
##Q3. Simple Calculations

In [26]:
average_age = all_ages.mean()
average_age

np.float64(50.0)

In [31]:
heart_rate = patients_data[ : , 1:2]
max_heart_rate = heart_rate.max()
max_heart_rate

np.int64(95)

In [35]:
 cholesterol_level = patients_data[ : , 2:3]
 mini_cholesterol_level = cholesterol_level.min()
 mini_cholesterol_level

np.int64(180)

In [36]:
##Part 2: Filtering & Conditions

In [40]:
np.where(blood_pressure_values > 130, "high_blood_pressure","normal")

array([['normal'],
       ['high_blood_pressure'],
       ['normal'],
       ['normal'],
       ['high_blood_pressure']], dtype='<U19')

In [45]:
np.where(cholesterol_level >= 240, "high_cholesterol_level","normal")

array([['normal'],
       ['high_cholesterol_level'],
       ['normal'],
       ['normal'],
       ['high_cholesterol_level']], dtype='<U22')

In [43]:
np.where(all_ages > 50, "older than 50","")

array([[''],
       ['older than 50'],
       [''],
       [''],
       ['older than 50']], dtype='<U13')

In [44]:
##Part 3: Thinking Like a Data Scientist

In [55]:
high_risk = (blood_pressure_values>140)| (cholesterol_level>240)
print(high_risk.any())

True
